### PR TITLE
Add note that featureLayer implements ILayer interface

### LINKED ISSUE #42: clarify the L.esri.featureLayer extends ILayer
http://leafletjs.com/reference.html#ilayer

so folks don't have to 'just know' about methods to add/remove from map.

### PR DESCRIPTION
**Pull request by tyleralves**
Fixes #42

### CODE REVIEW

**Comment by jgravois** [comment]
awesome.
if you're interested in taking a crack at Esri/esri-leaflet-heatmap-feature-layer#12, i'd be happy to help if you get stuck.

**Comment by tyleralves** [comment]
Sounds good, I'll take it.

**Comment by jgravois** [comment]
awesome!

just to be nitpicky on this one, it'd be helpful if you:
* followed our existing pattern for documenting extended Leaflet classes
* link directly to their [`1.0.0`](http://leafletjs.com/reference-1.0.0.html#layer) specific doc (where apparently `Layer` is no longer an interface, but rather a *base class*. 

example: [L.esri.basemapLayer](http://esri.github.io/esri-leaflet/api-reference/layers/basemap-layer.html) 

> Inherits from [`L.TileLayer`](http://leafletjs.com/reference.html#ilayer)

i should have been more clear about all this when i filed the ticket originally.

**Comment by tyleralves** [comment]
Updated per comments

**Comment by jgravois** [comment]
thx!

**Pull request merged**
