### PR TITLE
Updated website source repo link

### PR DESCRIPTION
**Pull request by tyleralves**

### CODE REVIEW

**Comment by jgravois** [comment]
thanks for this, but i think it'd probably be preferable to get rid of this `CONTRIBUTING.md` entirely and just link back to the one in the `esri-leaflet` repo.

how does that sound?
would you be game to lay down the change in another commit here?

**Comment by tyleralves** [comment]
Sure, cheers.

Should I add the link in `README.md` under the general ESRI contributing guidelines link?

**Comment by jgravois** [comment]
it looks like we're already linking back to esri-leaflet's `CONTRIBUTING.md`.  i'm not sure if there is another place here where we link to the wrong doc.  it's possible that all that needs done is to remove the duplicate file.

**Comment by tyleralves** [comment]
Agreed.

**Comment by tyleralves** [comment]
Creating new PR with deletion

**Comment by tyleralves** [comment]
@jgravois Is this an acceptable PR, or do I need to submit a new PR with only the delete commit?
Thanks for helping a new contributor!

**Comment by jgravois** [comment]
to quote [myself](https://twitter.com/geogangster/status/699664207319465984):

> github is a lot more fun when you realize pull requests don't have to be perfect initially (this goes for maintainers too).

back in the day contributors had to [`squash`](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request) their own commit history manually, but now the same thing is available to maintainers right in github's UI.

**Pull request merged**
