### PR TITLE
create first draft for secured services tutorial

### PR DESCRIPTION
**Pull request by pmacMaps**
Here's the first pass. Hopefully it's what you're thinking.  With the length of it, maybe ArcGIS Server and ArcGIS Online authenticated services tutorials need to be separate?

### CODE REVIEW

**Comment by jgravois** [comment]
very cool!

i'm a big fan of succinct tutorials so i'd definitely be on board with breaking this up.

**Comment by pmacMaps** [comment]
Do you want me to remove the existing authenticated services tutorial and put this one in a page called "Working with Authenticated Services for ArcGIS Server,", and creating a shell page for "Working with Authenticated Services for ArcGIS Online"?

**Comment by jgravois** [comment]
no need for another shell page. whichever one you want to work on first can replace the placeholder we have now.

**Comment by pmacMaps** [comment]
I removed the remaining references to error handling.  Thanks for cleaning up and simplifying my first draft.

Do you think it would make sense to create a tutorial at some point that deals with error handling?

**Comment by jgravois** [comment]
yes and yes. thanks for being so proactive and writing new tutorials. I guarantee lots of users find them very helpful!

**Comment by jgravois** [comment]
i renamed the files (`.PNG` > `.png`) and pushed to the production site. nice work!

**Pull request merged**
