### PR TITLE
added documentation for `ImageryClarity` option

### PR DESCRIPTION
**Pull request by gavinr**
https://github.com/Esri/esri-leaflet/pull/1047

### CODE REVIEW

**Comment by jgravois** [comment]
nice. you want to just push another commit here with the info for `Popup`?

**Comment by gavinr** [comment]
yes, good idea - will do

**Comment by gavinr** [comment]
@jgravois please take a look if the summary in that last commit is accurate. if it looks good i'm happy to merge and deploy again. thanks!

**Comment by jgravois** [comment]
:shipit:. thanks!

**Pull request merged**
