### PR TITLE
Fix typo in Query API page ("overlap" to "overlaps")

### PR DESCRIPTION
**Pull request by pmacMaps**
Working on a project, I realized that there is a typo on the [Query API](https://esri.github.io/esri-leaflet/api-reference/tasks/query.html) page.  It references "overlap" as a valid query type.  But as you can see in the image below, "overlap" is not a valid type.  It appears "overlaps" is the correct way to reference this query type.

overlap-not-function

### CODE REVIEW

**Comment by pmacMaps** [comment]
Looks like it's mostly npm/node issues.

**Comment by gavinr** [comment]
I'm not sure if it's related, but there's an [impending 31-December deadline for Travis-ci.org usage](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom) ... we should probably switch over to GitHub actions for the automated linting testing. I'll merge this for now and open a separate issue for the Travis error.

**Comment by gavinr** [comment]
Confirmed that this change is correct per the code: https://github.com/Esri/esri-leaflet/blob/f572dbad34d6aef5b94eface5c0b73da5bbd9caa/src/Tasks/Query.js#L69

**Comment by gavinr** [comment]
Thanks @pmacMaps!

**Pull request merged**
