### PR TITLE
Fix Some Map Services

### LINKED ISSUE #227: "Points as a heatmap" sample broken (service set to private)
* Browser and version:

Chrome Version 75.0.3770.100

* Version of Leaflet (`L.version`):

* Version of esri Leaflet (`L.esri.VERSION`):

1.0.4, 2.0.3, `master`?

Steps to reproduce the error:

1. Go to: http://esri.github.io/esri-leaflet/examples/visualize-points-as-a-heatmap.html

What happens is [X].

No heatmaps are shown

I was expecting [Y].
An heatmap

(if possible, create a [jsbin](http://jsbin.com/dagilag/edit?html,output) that demonstrates the problem)

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:

[webpack](https://webpack.github.io/), [browserify](http://browserify.org/), [RequireJS](http://requirejs.org/)?

There are a lot of these demo's/examples that are not working. 
Is there a reason for this (not supported anymore?).
If you want a complete list of all the demo's that are not working I can provide that.

### PR DESCRIPTION
**Pull request by pmacMaps**
This starts to resolve #227 and #226.  However, there are more broken examples that use those Portland services.

Feel free to tweak my changes as you want.  I'm not a huge fan of the earthquakes symbol, but it's something.

### CODE REVIEW

**Comment by pmacMaps** [comment]
It is a `png`.  The existing site uses the `https://esri.github.io/esri-leaflet/img/[filename]` href attribute.  I wasn't sure if the relative paths would work or not.

**Comment by pmacMaps** [comment]
I took another look.  It looks like the file in the `\src\img` directory was messed up.  I replaced it with an actual image file.

This will hopefully resolve the issue.

**Comment by gavinr** [comment]
Thanks @pmacMaps! I switched it back to the full path because the code may be copy/pasted by users who are trying to use the sample directly from the site:
image

**Comment by gavinr** [comment]
deployed - these samples now working again - thanks @pmacMaps!

- https://esri.github.io/esri-leaflet/examples/clustering-feature-layers.html
- https://esri.github.io/esri-leaflet/examples/visualize-points-as-a-heatmap.html
- https://esri.github.io/esri-leaflet/examples/simple-feature-layer.html
- https://esri.github.io/esri-leaflet/examples/styling-feature-layer-points.html
- https://esri.github.io/esri-leaflet/examples/getting-service-metadata.html
- https://esri.github.io/esri-leaflet/examples/feature-layer-popups.html

**Pull request merged**
